### PR TITLE
Shield is OneHandWeapons

### PR DESCRIPTION
**Pull request by flier268**

### CODE REVIEW

**Comment by HiMarioLopez** [comment]
Howdy hey, thanks for putting in your PR!

I want to clarify that the decision to omit one-handed shields from the filter rules for the weapon set requirements of the recipes was fully intended to be the default.

We only include a subset of 1-handed weapons, the ones that are sized 1x3 (3 units, ergo 6 units for a set) to save stash space, or a 2x3 2-handed weapon. And we omit the shields for the same reasons, since the smallest ones will always be 2x2 (4 units big, with the smallest weapon = 7 units)

An iteration of this PR could be to include a UI option that allows the user the option to ignore these stash space optimizations and include any weapon and any shield in the filter rules. That would be cool!

Let me know if you want any help with the design, more than happy to help.

Mario

**Comment by flier268** [comment]
I think the stash space problem is user's problem. 
A tool just need to care for recipes works or not, user put some 2*4 size item into the stash, means user want to sell that

**Comment by HiMarioLopez** [comment]
I do agree, but when removing old functionality or modifying pre-existing behavior I'd want to make sure I make the necessary changes to the UI to allow to the user to revert back to how it was previously. This particular change would require some sort of new option in the UI.

I'm open to including this feature in the future, 100%!

**Comment by flier268** [comment]
But I don't know how to modify your code.

I had review your code for 10 min in first time.Split project to three part is a good idea, but I found that you does not use filter to skip item, so add this option is not easy for me.

Add two line to fit my need, that can let me feel satisfied, I don't want to do more for this, but add a task to pull and release automatucally in my fork.

By the way,I found two model that can deserialize json from API, and a lot of magic number, so I had a little confused.

**Comment by HiMarioLopez** [comment]
I agree, adding full features takes time and is more involved than modifying a few lines of code! 😅

I think that if you want that default behavior, you are more than welcome to fork the code to your own repository and build it out and run that version of the app locally.

As for the full implementation as discussed here, I do not have any plans to prioritize this soon. I will keep this in mind for future releases though.

**Pull request closed without merging**
