### PR TITLE
mutliple modifiers functional for toggle

### PR DESCRIPTION
**Pull request by Nyxion**
Adding support for multiple modifiers `CTRL,ALT,SHIFT` win eventually if wanted. 

Also it only runs it once when pressed, so it doesnt re-open window every single time the key is checked.

Dont know why it doesnt work on single modifier or no modifier, fixing later.

### CODE REVIEW

**Comment by Nyxion** [comment]
Still need to see why its not running only once

**Review by Nyxion — COMMENTED** [review]
Can still be improved with refactoring and single instance still feels clunky as shit.

**Comment by Nyxion** [comment]
On discord with same name if you wanna shout at me, ty.

**Comment by HiMarioLopez** [comment]
Howdy, just letting you know I'm traveling for work and personal for a bit. I'll be back to review this after Thursday. Thanks for your contribution!

**Comment by HiMarioLopez** [comment]
This PR branch has become stale. While we weren't able to use your code, I really do appreciate your willingness to contribute to the project!

**Pull request closed without merging**
