### PR TITLE
Fix adding newlines to the filter with every fetch

### PR DESCRIPTION
**Pull request by MarcLandis**

### CODE REVIEW

**Comment by kosace** [comment]
Hello,

the new line in the separator could lead to problems. But you are right. I forgot to remove the new lines from the exalted recipe. Will fix asap.

**Comment by MarcLandis** [comment]
I testet the change for an hour and it was working without issues. If you have a better fix, then just close my pull request.

**Comment by kosace** [comment]
I have pushed a fix 1 minute ago. 

You are right it would work indeed. It actually makes no difference if you add new lines at the end and then search for the new lines and delete them (your pull) or if you just never add new lines at the end :)

You can join the discord btw if you want

**Comment by kosace** [comment]
okay yours is better, i had yet another error in there

**Pull request closed without merging**
