### PR TITLE
Filter refactor

### PR DESCRIPTION
**Pull request by george-delchev**
I've moved both the section generation and the loot filter update to the manager. 
Next goal is to move some strings, as you mentioned, but I have no idea how often they change and break. Never really messed with filters before.
I want to also try to use the real API instead of the sessions thingy at some point, might take a look these weeks when I have time.
Also looking at the way sets are generated since there are some funky stuff going on there atm.

Anyway, when you have the time, I will try to tackle stuff that won't conflict with this for now.

### CODE REVIEW

**Comment by HiMarioLopez** [comment]
Yeah for rate at which filter strings are gonna change it's kind of hard to say, but given a big expac just came out I think it's safe to assume no major filter changes will be made for the next year or so.  I'll take a look at this when I have a chance this week!

edit: also just want to mention thank you so much for what you do, mate. It really is helping the community out! Cheers

**Comment by HiMarioLopez** [comment]
Starting my development back up as we inch closer to the release of 3.18. Any updates on this PR? Do you think it's ready to merge into dev?

EDIT: To clarify, I love the direction we are taking with this organization of the filter logic. I want to work to make some bigger project structure changes and move a loooooot of stuff from the big "Model" folder into their own nested directories for better code organization.

**Comment by george-delchev** [comment]
I haven't had time the past weeks to do more stuff, but I did some test before I send the PR so should be good.
Even if there are some small issue, should be much easier to identify and fix now.
Been wondering if its worth trying to make some automated tests, that check if it adds the right sections depending on the missing items. Think that requires creating interfaces for options and what not, so I can mock them. Have to give it a go when I find time.
Anyway, think it's fine to merge as is for now, unless you see some things you want changed.

Also, feel free to assign me some stuff you feel are priority before new league and I'll see what I can do about them.

**Comment by HiMarioLopez** [comment]
Awesome. Gonna mark this as ready for review and merge it into our DEV branch.

Do you have a Discord? I can better coordinate with you some major changes I want to be making after speaking with the lead dev for PoeLurker. He had some awesome design and architecture decisions for that app and I want to adopt a lot of those ideas to clean up ours!

**Comment by george-delchev** [comment]
Yes, ﻿use it only for games, so yeh.
Adelia\lorddelio#6156

**Pull request merged**
