### PR TITLE
Add Shields as One Handed Weapons

### LINKED ISSUE #235: Shields not included in sets...
Hi, 
i'm having a problem with the app, i've a lot of shields in my recipe tabs, but the program is not including them in sets, it just consider the weapons only, i've tried 3 and 6 space weapons, but no 4 space shields.

image

i had the 1.2.4 version, unistalled and installed the new 1.2.6, but i've the same behaviour, it's an issue or i can't use shields for sets?
thanks for the help

### PR DESCRIPTION
**Pull request by Aradiv**
Shields work like One-Handed Weapons for the Recipes.

Fixes #235

### CODE REVIEW

**Comment by HiMarioLopez** [comment]
So, we don't have shields on the recipe to save space. This was a design decision.

The smallest shields will take up 4 units of space in the inventory/stash (2x2), with the smallest weapon being 3 units (3x1), we'll have a set min equaling 7 total units.

With a two-hander you take up 6 units, or with 2 min-sized one-handed weapons you will take up the same 6 units. 

I think to stay consistent with that I'll look at taking out the one-handed thrusting weapons from the app, since those can take up to 4x1 spaces.

**Comment by HiMarioLopez** [comment]
Appreciate you taking a look at the code and putting in your contribution. Let me know if you have any further questions, my DMs are always open!

**Comment by Aradiv** [comment]
i often lack weapons and would prefer to be able to just complete the recipes with items i already have in my stash no matter the size so currently if i see a shield i click on the weapon the tool tells me to pick put it right back and then pick a shield instead.

**Comment by Aradiv** [comment]
Maybe instead of removing the ability to interact with "large items" at all add special item classes
OneHandedLarge and TwoHandedLarge and let the user choose if the tool should include them or not.

**Comment by valen214** [comment]
I wish I could still use the shield in the recipe, despite of not picking up, because sometimes when you are in later stage of the game you might pick up everything from below lv74.

I would probably look at it after sometime.

**Pull request closed without merging**
