### PR TITLE
Fix for CLIPBRD_E_CANT_OPEN exception

### PR DESCRIPTION
**Pull request by Essyer**
Found solution on stack: https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid
Seems to be working but someone else needs to confirm.

### CODE REVIEW

**Comment by Logonius** [comment]
Thx

**Comment by Hydrant777** [comment]
Hello, thank you for having a look into this. Love the app, and though it wasn't easy to setup, it workd very well the past leagues. Now it just says access forbidden - doesn't work with my session ID. Tried to reload/clear cache, nothing worked. But I also received the exception you worked on somehow.
And I'd love to test it but I have no clue how to build the app from the source code :(
Tried to install the .NET SDKs, NuGet, WiX and all the stuff that the compiler has been complaining about but to no avail. Spent about 2 hours figuring it out - seems I would need a dummy manual on howto do it :)

**Comment by Essyer** [comment]
> Hello, thank you for having a look into this. Love the app, and though it wasn't easy to setup, it workd very well the past leagues. Now it just says access forbidden - doesn't work with my session ID. Tried to reload/clear cache, nothing worked. But I also received the exception you worked on somehow. And I'd love to test it but I have no clue how to build the app from the source code :( Tried to install the .NET SDKs, NuGet, WiX and all the stuff that the compiler has been complaining about but to no avail. Spent about 2 hours figuring it out - seems I would need a dummy manual on howto do it :)

Hello,
Make sure your session is still valid, it expires after some time. For me it was enough to install WiX Toolset build tools and WiX Toolset Visual Studio Extension for Visual Studio 2019 from this page: https://wixtoolset.org/releases/
Let me know what kind of errors do you get when you try to build this tool.

**Comment by Hydrant777** [comment]
Hello,
Splendid. Thank you for helping me out. I did as you suggested and the build finished without any issues.
I also fixed the issue with my session ID - it was copied with the "POESESSID:" name so that's why it wasn't working.

Anyway I can confirm that you fixed the error (at least for the two of us). The tool works well.. except the loot filter color manipulation, but that's another topic :)

Thanks again for your support.

**Comment by HiMarioLopez** [comment]
Howdy hey! We're trying to get some admin stuff out of the way so me and a few other folks can take the reigns on the project and push out some updates before league launch.

I just want to thank you for your contributions and will try my best to get them into the project before 3.17 league launch.

**Pull request merged**
